packages:
  - .

catalog:
  '@eslint/js': ^9.34.0
  '@eslint/json': ^0.13.1
  '@eslint/markdown': ^7.2.0
  '@types/jest': ^30.0.0
  '@types/node': ^24.3.0
  '@typescript-eslint/eslint-plugin': ^8.40.0
  '@typescript-eslint/parser': ^8.40.0
  '@vitest/eslint-plugin': ^1.3.4
  eslint: ^9.34.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-jest: ^29.0.1
  eslint-plugin-perfectionist: ^4.15.0
  eslint-plugin-pnpm: ^1.1.1
  eslint-plugin-prettier: ^5.5.4
  eslint-plugin-promise: ^7.2.1
  eslint-plugin-sonarjs: ^3.0.4
  eslint-plugin-unicorn: ^60.0.0
  globals: ^16.3.0
  jest: ^30.0.5
  jiti: ^2.5.1
  pnpm: ^10.15.0
  prettier: ^3.6.2
  prettier-plugin-organize-imports: ^4.2.0
  ts-jest: ^29.4.1
  ts-node: ^10.9.2
  typescript: ^5.9.2
  typescript-eslint: ^8.40.0
  vitest: ^3.2.4

catalogs:
  conflicts_conflicts_eslint_:_:
    eslint: ''
  conflicts_conflicts_eslint_:_9_34_0:
    eslint: 9.34.0
  'conflicts_conflicts_eslint_:_x:':
    eslint: 'x:'
  'conflicts_eslint_:':
    eslint: ':'
  'conflicts_eslint_x:':
    eslint: 'x:'
